name: Makefile CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run unit tests
      working-directory: ./patient-service
      run: make test-unit

    - name: Run integration tests
      working-directory: ./patient-service
      run: make test-integration

    - name: Generate test report
      working-directory: ./patient-service
      run: make test-report

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: patient-service/target/site/

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      working-directory: ./patient-service
      run: make build

    - name: Push Docker image
      working-directory: ./patient-service
      run: make push